//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application started.
        /// </summary>
        internal static string ApplicationStarted {
            get {
                return ResourceManager.GetString("ApplicationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appsettings.json.
        /// </summary>
        internal static string AppSettingsFile {
            get {
                return ResourceManager.GetString("AppSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding assignment: {0}.
        /// </summary>
        internal static string AssignmentAddError {
            get {
                return ResourceManager.GetString("AssignmentAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment added successfully!.
        /// </summary>
        internal static string AssignmentAddSuccess {
            get {
                return ResourceManager.GetString("AssignmentAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos;? This cannot be undone..
        /// </summary>
        internal static string AssignmentDeleteConfirmation {
            get {
                return ResourceManager.GetString("AssignmentDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting assignment: {0}.
        /// </summary>
        internal static string AssignmentDeleteError {
            get {
                return ResourceManager.GetString("AssignmentDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment deleted successfully..
        /// </summary>
        internal static string AssignmentDeleteSuccess {
            get {
                return ResourceManager.GetString("AssignmentDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment submitted successfully!.
        /// </summary>
        internal static string AssignmentSubmitSuccess {
            get {
                return ResourceManager.GetString("AssignmentSubmitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save changes: {0}.
        /// </summary>
        internal static string AssignmentUpdateFail {
            get {
                return ResourceManager.GetString("AssignmentUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        internal static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export CSV: {0}.
        /// </summary>
        internal static string CSVExportError {
            get {
                return ResourceManager.GetString("CSVExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV exported successfully!.
        /// </summary>
        internal static string CSVExportSuccess {
            get {
                return ResourceManager.GetString("CSVExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_Assignments.csv.
        /// </summary>
        internal static string CSVFilename {
            get {
                return ResourceManager.GetString("CSVFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Files (*.csv)|*.csv.
        /// </summary>
        internal static string CSVFilter {
            get {
                return ResourceManager.GetString("CSVFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultConnection.
        /// </summary>
        internal static string DefaultConnection {
            get {
                return ResourceManager.GetString("DefaultConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update profile. Please try again..
        /// </summary>
        internal static string EditUserFail {
            get {
                return ResourceManager.GetString("EditUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam.
        /// </summary>
        internal static string Exam {
            get {
                return ResourceManager.GetString("Exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Error: {0}.
        /// </summary>
        internal static string GradesSaveError {
            get {
                return ResourceManager.GetString("GradesSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save grades. Check the debug console..
        /// </summary>
        internal static string GradesSaveFail {
            get {
                return ResourceManager.GetString("GradesSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades saved successfully!.
        /// </summary>
        internal static string GradesSaveSuccess {
            get {
                return ResourceManager.GetString("GradesSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homework.
        /// </summary>
        internal static string Homework {
            get {
                return ResourceManager.GetString("Homework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓.
        /// </summary>
        internal static string IconBird {
            get {
                return ResourceManager.GetString("IconBird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✕.
        /// </summary>
        internal static string IconCross {
            get {
                return ResourceManager.GetString("IconCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠.
        /// </summary>
        internal static string IconDanger {
            get {
                return ResourceManager.GetString("IconDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ℹ.
        /// </summary>
        internal static string IconInfo {
            get {
                return ResourceManager.GetString("IconInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address.
        /// </summary>
        internal static string LoginEmailError {
            get {
                return ResourceManager.GetString("LoginEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password. Please check your credentials and try again..
        /// </summary>
        internal static string LoginInvalidCredentialsError {
            get {
                return ResourceManager.GetString("LoginInvalidCredentialsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        internal static string LoginPasswordError {
            get {
                return ResourceManager.GetString("LoginPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address.
        /// </summary>
        internal static string RegisterEmailAddress {
            get {
                return ResourceManager.GetString("RegisterEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your first and last name.
        /// </summary>
        internal static string RegisterNameError {
            get {
                return ResourceManager.GetString("RegisterNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password.
        /// </summary>
        internal static string RegisterPasswordError {
            get {
                return ResourceManager.GetString("RegisterPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your role (Student or Teacher).
        /// </summary>
        internal static string RegisterRoleError {
            get {
                return ResourceManager.GetString("RegisterRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration error: {0}.
        /// </summary>
        internal static string RegistrationError {
            get {
                return ResourceManager.GetString("RegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed. This email may already be registered..
        /// </summary>
        internal static string RegistrationFailError {
            get {
                return ResourceManager.GetString("RegistrationFailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created successfully! Redirecting to login....
        /// </summary>
        internal static string RegistrationSuccess {
            get {
                return ResourceManager.GetString("RegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        internal static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Error.
        /// </summary>
        internal static string SyncError {
            get {
                return ResourceManager.GetString("SyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        internal static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string TitleIsRequired {
            get {
                return ResourceManager.GetString("TitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete your account? This action cannot be undone..
        /// </summary>
        internal static string UserDeleteConfirm {
            get {
                return ResourceManager.GetString("UserDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete account. Please try again later..
        /// </summary>
        internal static string UserDeleteError {
            get {
                return ResourceManager.GetString("UserDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deleted successfully. Logging out....
        /// </summary>
        internal static string UserDeleteSuccess {
            get {
                return ResourceManager.GetString("UserDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name fields cannot be empty..
        /// </summary>
        internal static string UserEditNameError {
            get {
                return ResourceManager.GetString("UserEditNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully!.
        /// </summary>
        internal static string UserEditSuccess {
            get {
                return ResourceManager.GetString("UserEditSuccess", resourceCulture);
            }
        }
    }
}
